; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, CheckBox, vABBLE x304 y32 w120 h22, CheckBox
Gui Add, ComboBox, x174 y119 w120, ComboBox
Gui Add, MonthCal, gAble x346 y272 w225 h160
Gui Add, Text, x215 y225 w120 h23 +0x200, Text
Gui Add, UpDown, x167 y280 w17 h20  -16, 1
Gui Add, DropDownList, x48 y1 w120, DropDownList||

Gui Show, w620 h420, Window
Return

GuiEscape:
GuiClose:
    ExitApp
